name: Deploy to TER

on:
  push:
    tags:
      - "**"

jobs:
  TER:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Determine tag"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""

      - name: Install TYPO3 Tailor Extension
        run: composer global require typo3/tailor --prefer-dist --no-progress --no-suggest

      - name: Deploy to TER
        env:
          TYPO3_API_USERNAME: ${{secrets.TYPO3_ORG_USERNAME}}
          TYPO3_API_PASSWORD: ${{secrets.TYPO3_ORG_PASSWORD}}
        run: |
          echo -e "Preparing upload of release ${{ steps.determine-tag.outputs.tag }} to TER\n";

          # Install Tylor client
          composer global require typo3/tailor
          # Build extension files
          composer extension-release

          # Upload
          TAG_MESSAGE=`git log -1 --pretty=%B`
          echo "Tag-Message: ${TAG_MESSAGE}"
          echo "Uploading release ${{ steps.determine-tag.outputs.tag }} to TER"
          $HOME/.composer/./vendor/bin/tailor set-version ${{ steps.determine-tag.outputs.tag }}
          $HOME/.composer/./vendor/bin/tailor ter:publish ${{ steps.determine-tag.outputs.tag }} imgix --comment "$TAG_MESSAGE"
